site_name: '${{values.app_name}}'
site_description: Documentation for the ${{values.app_name}} service
repo_url: https://github.com/lordcommandermv/${{values.app_name}}
edit_uri: edit/main/docs

nav:
  - Overview:
    - Getting Started: 'docs/index.md'

plugins:
  - techdocs-core
